INSERT INTO public.hotels ("name",country,region,city,street,house,description,phone_num,email,web_site,"family",children,the_youth,old_friends,comfort,distance,price,activity,safety,active_recreation_on_the_water,fishing,football,volleyball,table_tennis,tennis,cycling,distance_from_kazan,cost_of_stay_per_day,short_description,main_feature) VALUES
                                                                                                                                                                                                                                                                                                                                                           ('Глемпинг BEST GLAMP','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','Р”РќРў Р’РµС‚РµСЂР°РЅ','','"ВestGlamp - это место силы и слияния человека с лесом, водой и невероятной природой.

Создавая проект, мы фокусировались на сохранении первозданного леса с сохранением комфорта для гостей. В 50 минутах езды от Казани Вы окажитесь в поселке Васильево, Зеленодольского района, прямо на мысу у реки Волга. На участке комплекса есть сотни дубов и сосен, большинство из которых живут здесь уже более 70 лет.

Ежедневное ""лесное купание"" (прогулки в тишине леса) позволит вам отвлечься от городской суеты и перезагрузится, а кто желает совместить отдых с активностью, есть футбольное поле советских времен, снегоходы и гидроциклы. Береговая зона обустроена для прогулок и лежаков. Каждый желающий сможет не только наблюдать за рекой и небом, но и даже заняться рыбалкой. Также у нас есть невероятная воздушная тропа, где на высоте 3 метров над землей вы сможете прогуляться между крон дубов. Такая прогулка впечатляет как днем, так и вечером, так как есть ненавязчивая подсветка по прогулочным тропам.

Проснувшись в одном из домиков, попробуете завтрак, далее мы вам предложим обед или ужин от нашего повара. Для этого есть специальный геокупол на 30 человек, где можно будет собираться не только для приема вкусных блюд, но и для проведения киновечеров и совместных игр.

В общей сложности мы находимся на территории 8 га, и на данный момент имеем 5 видов домиков. Одноэтажный и двухэтажный Tiny Houses, A-frame, Купольный и Зеркальный домик на дереве. Каждый домик оснащен всем необходимым для комфортного отдыха. У каждого есть своя душевая с санузлом, кровать superking size, телевизор и wifi, террасой и сеткой-гамаком, а некоторые домики имеют свою дровяную печку и диван, который идеально подойдет для размещения пар с детьми.

В 25 минутах езды от нас остров Свияжск и Планетарий. Хотя оказавшись у нас, вы и так найдете все необходимое для гармоничного отдыха и расслабления всего организма."
','+7 (986) 900-10-65','','https://bestglamp.aqulas.me/',20,15.48,16,23,15,-4.6,-15.6,21,3,6,1,1,1,0,0,0,26,6500,'ВestGlamp - это место силы и слияния человека с лесом, водой и невероятной природой.','Домик на двоих от 13000 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('URMAN CAMP','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','Р—РµР»РµРЅРѕРґРѕР»СЊСЃРє','СЃ. Р‘РѕР»СЊС€РѕР№ РљСѓР»СЊР±Р°С€','','"Представьте, что вы оказались в березовой роще, где щебечут птички, ветер играет листвой и пробивается родник. При этом, в вашем распоряжении мягкая постель, с белоснежными простынями, личный СПА, отдельная кухня и ванная комната.

Можно развести камин, укутаться в плед и взять книгу, а можно провести вечер в чане с горячей водой, глядя на звездное небо или пересматривая любимые фильмы."
','+7 (967) 555-97-50','UrmanCamp@ya.ru','https://urman.camp/',12,7.96,4,7,8,-7.2,-8.4,4,2,0,0,0,0,0,0,1,52,3500,'Представьте, что вы оказались в березовой роще, где щебечут птички, ветер играет листвой и пробивается родник. При этом, в вашем распоряжении мягкая постель, СПА, отдельная кухня и ванная комната.','Сафари тент на двоих – 6900 руб., Дом с чаном на 4 – 14000 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('"Камский Трофей"','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°РјСЃРєРѕРµ РЈСЃС‚СЊРµ','СѓР». Р‘РѕР»СЊС€Р°СЏ Р’РѕР»РіР°','4','«THE Камский» – это современный трёхзвёздочный отель, идеальное место для загородного отдыха вдали от повседневной суеты. В месте слияния Волги и Камы вы сможете насладиться красивыми видами, высоким уровнем сервиса и SPA-процедурами.
','+7 (800) 600-13-24','kama_trophy@mail.ru','РєР°РјСЃРєРёР№-С‚СЂРѕС„РµР№.СЂС„',18,19.02,17,20,20,-9.9,-15.6,14,6,4,1,0,0,0,0,1,99,6500,'Это современный трёхзвёздочный отель, идеальное место для загородного отдыха вдали от повседневной суеты. В месте слияния Волги и Камы вы сможете насладиться красивыми видами, высоким уровнем сервиса и SPA-процедурами.','Номер на двоих – 6500 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Отель KOL GALI RESORT&SPA','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','Р“. Р‘РћР›Р“РђР ','РЈР›. РџР РР‘Р Р•Р–РќРђРЇ','1','Пятизвездочный курортный SPA-отель Kol Gali Resort & Spa был открыт в 2018 г. Отель расположен на живописном берегу Волги в городе Болгар Республики Татарстан. Общая территория комплекса составляет около 25 гектаров. Основой концепции отеля мы выбрали экологичность, натуральность, заботу о здоровье наших гостей и благополучии окружающей среды, соединение культуры и традиций Востока с европейским гостеприимством. Для Вашего наиболее комфортного пребывания мы предлагаем номера, оборудованные системами «Умный дом» на базе Яндекс. Алиса, Wi-Fi замки, а также интерактивное телевидение Hoteza. Также в App Store и Google Play доступно интегрированное мобильное приложение Kol Gali Resort & SPA, в котором возможно узнать всю информацию о комплексе и г. Болгар, а также сделать заказ. Для Вашего удобства все меню доступны в электронном формате, необходимо лишь отсканировать QR-код. С заботой об окружающем мире мы используем новейшие передовые технологии, такие как автоматизированные системы управления зданием (BMS), что помогает экономить природные ресурсы. Управление температурным режимом, а также освещением в номерах и общественных зонах производится с планшетов.
','8 843 473 15 77','RESERVATION@KOLGALIRESORT.COM','http://kolgaliresort.ru/',21,20.4,12,19,18,-18,-28.8,14,5,1,1,0,0,1,1,1,180,12000,'Пятизвездочный курортный SPA-отель Kol Gali Resort & Spa был открыт в 2018 г. Отель расположен на живописном берегу Волги в городе Болгар Республики Татарстан.','Номер на двоих от 25500 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Minger-Tower','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','СЃРµР»Рѕ РњРёРЅРіРµСЂ','','"Добро пожаловать в Minger Med Spa - оздоровительный комплекс премиум-класса, который предлагает уникальный метод оздоровления тела, души и разума. Мы разрабатываем авторские программы, направленные на оздоровление организма и прививание нашим гостям привычки здорового питания и образа жизни, в единении с уникальным природным местом.

Расположенная вдали от городского шума и суеты, в 90 км. от Казани, в селе Мингер Сабинского района, Minger Med Spa - это территория, где каждый может ощутить себя в своем месте силы и получить заряд энергии для новых свершений."
','+7 (843) 562-0-300','RESERVATION@MINGERMEDSPA.RU','https://minger.ru/',20,19.6,13,19,20,-12,-17.52,9,5,3,1,0,0,0,0,1,120,7300,'Загородный комплекс Minger Tower – территория здоровья, комфорта и единения с природой. Хвойный лес, река и десятки кристальных прудов с артезианскими источниками. ','Бунгало с 3-х разовым питанием от 14600 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Глемпинг Дикая дача','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','РЎРќРў РђСЂС…РёС‚РµРєС‚РѕСЂ','','Глэмпинг «дикая дача» — сочетание отдыха на природе и привычного горожанам комфорта в необычных сооружениях.
Здесь царит атмосфера уюта, тепла и спокойствия.
Философия глэмпинга построена на желании гостей выбраться на природу, отвлечься от городской суеты и перезагрузиться.Сюда можно приехать одному или с любимым человеком, чтобы побывать в тишине в самом отдалённом домике глэмпинга.Для любителей отдыха в компании друзей или семьи идеально подойдёт юрта
Или вигвам. Вместе можно насладиться готовкой на мангале и вечерними посиделками у костра под гитару.
Глэмпинг расположен в лесной местности,
Где летом гости любят собирать ягоды, а в пешей доступности расположено озеро для катания на сапборде.
Когда стемнеет, весь глэмпинг собирается для просмотра
Фильмов на большом экране под звёздным небом!

Глэмпинг «дикая дача» — сочетание отдыха на природе и привычного горожанам комфорта в необычных сооружениях.
Здесь царит атмосфера уюта, тепла и спокойствия.
Философия глэмпинга построена на желании гостей выбраться на природу, отвлечься от городской суеты и перезагрузиться.Сюда можно приехать одному или с любимым человеком, чтобы побывать в тишине в самом отдалённом домике глэмпинга.Для любителей отдыха в компании друзей или семьи идеально подойдёт юрта
Или вигвам. Вместе можно насладиться готовкой на мангале и вечерними посиделками у костра под гитару.
Глэмпинг расположен в лесной местности,
Где летом гости любят собирать ягоды, а в пешей доступности расположено озеро для катания на сапборде.
Когда стемнеет, весь глэмпинг собирается для просмотра
Фильмов на большом экране под звёздным небом!','+7 987 235 33 29','info@dikayadacha.ru','https://dikayadacha.ru/',16,10.4,10,14,7,-5,-4.8,9,3,1,1,1,0,0,0,1,30,2000,'Философия глэмпинга построена на желании гостей выбраться на природу, отвлечься от городской суеты и перезагрузиться.','Домик на двоих от 3400 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Глэмпинг "ЛЕБЕДИНО ЭКО-Тур"','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РђР»РµРєСЃРµРµРІСЃРєРёР№ СЂР°Р№РѕРЅ','СЃ.Р›РµР±РµРґРёРЅРѕ','','"Глэмпинг «Lebedino ECO» располагается в удивительно красивом месте, на берегу реки Кама возле села Лебедино Алескеевского района, среди лесов и полей.
У нас можно насладиться тишиной, свежим воздухом и красивыми закатами. По вечерам можно наслаждаться бескрайним звездным небом.

Отдых в «Lebedino ECO»идеально подходит для семей с детьми и влюбленных пар. Даже в одиночку здесь можно побыть в тишине, собраться с мыслями или просто отдохнуть от суеты большого города.

В «Lebedino ECO» есть все необходимое для комфортного проживания."
','+7 (939) 735-66-36','zakaz@lebedino.ru','https://lebedino.ru/',16,11.8,11,16,16,-11,-9,9,0,1,1,0,0,0,0,1,110,3750,'Глэмпинг «Lebedino ECO» располагается в удивительно красивом месте, на берегу реки Кама возле села Лебедино Алескеевского района, среди лесов и полей.','Домик на четверых от 7000 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Глемпинг halal resort','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РїРѕСЃ. РљР°РјСЃРєРёР№','В СѓР». РљСѓСЂРѕСЂС‚РЅР°СЏ','2','Halal Resort - это 9 комфортабельных палаток со всеми необходимыми удобствами. На территории глэмпинга имеется спортивная и детская площадки, место для приготовления пищи, обеденная терраса с видом на Каму, гриль-зона, комфортабельные туалеты и душевые с горячей водой, костровая зона, а также молельная комната.
','+7 (919) 627-92-25','halal.glamping@gmail.com','https://halalresort.ru/',17,14.8,10,14,10,-6,-7.2,8,1,1,1,0,1,0,1,1,60,3000,'Глэмпинг Halal Resort – это место для семейного отдыха, соответствующее стандартам халяль.','Сафари-тент на двоих (до 3-х чел.) – 4500 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Кемпинг Дикая собака','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','РЎС‚Р°СЂРѕРµ РџРѕР±РµРґРёР»РѕРІРѕ, РЎРќРў РћРЎРўР РћР’РћРљ','','На окраине Казани в селе Старое Победилово вдоль берега Волги расположено множество островов и полуостровов
В 60-е годы здесь обосновались дачники, и вот уже в третьем поколении они живут на островах словно в отдельном мире, где время остановилось. Острова соединены между собой каналами, по которым передвигаются на лодках местные жители, поэтому эти места иногда называют Татарской Венецией.

На одном из этих островов на самом берегу Волги в этом сезоне мы и разместили наш лагерь.','+7 (917) 249-83-85','albina@dingocamp.ru','https://www.dingocamp.ru/',13,12.72,9,11,6,-1.4,-3.84,9,3,3,1,0,0,1,1,1,14,1600,'5 уютных семейных шатров и 2 шатра на двоих, вигвам, баня, кухня и гриль-зона, веранда совмещенная с библиотекой, собственный пирс','Шатер на двоих от 3900 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('Глемпинг MY AHOME','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','РїРѕСЃ. РЁСѓСЂР°РЅ','','"Глэмпинг для уединенного отдыха “My Ahome” с оригинальным круглым домом в виде прозрачного шара находится в 60 км от Казани на первой линии берега Камы, в поселке Шуран Лаишевского района Татарстана.

Для проживания на территории лагеря оборудованы 2 треугольных домика A-Frame и прозрачный баббл-шатер для двоих, из которого можно любоваться на звезды. Внутри он оборудован кондиционером, помимо кровати есть туалет, раковина с теплой водой, холодильник, микроволновка, чайник, посуда и проектор. Душа в номере нет.

У домика есть купель фурако с подсветкой, мангал, кресла и стол. Цена аренды баббл-шара составляет 8000 руб/сутки вс-чт, 9000 руб/сутки в пт и10000 руб/сутки в сб. В стоимость проживания включено пользование баней и фурако. Проживание с детьми в данном домике невозможно.

Домики A-Frame вмещают до 4 человек. Внутри есть спальня с двухместной кроватью, гостиная с диваном, полностью оборудованной кухней и обеденной зоной, ванная комната, кондиционер. У домиков есть индивидуальные мангальные площадки с дровами и фурако (входит в стоимость проживания). Цена аренды составляет 9500 руб/сутки вс-чт за двоих и 11000 руб/сутки пт-сб. Дополнительное место стоит 1000 руб/сутки. Дети до 12 лет живут бесплатно.

В лагере можно попариться в бане (2000 руб/час, минимум 2 часа). Рядом есть песчаный пляж."
','7 (995) 008-23-05','https://t.me/edagda','https://edagda.ru/kazan/article/obzor-glempinga-my-ahome',15,10.8,7,12,15,-8,-13.2,5,6,1,1,0,0,0,0,0,60,5500,'My Ahome – это глэмпинг, где можно отдохнуть и спокойно провести время всей семьей. В этом глэмпинге есть 2 домика A-frame со своей мангальной зоной и подогреваемой купелью Фурако. Фишкой является прозрачный круглый домик, в котором можно наблюдать на звезды. Рядом терраса с подогреваемой купелью и подсветкой.','Домик на двоих от 11000 руб');
INSERT INTO public.hotels ("name",country,region,city,street,house,description,phone_num,email,web_site,"family",children,the_youth,old_friends,comfort,distance,price,activity,safety,active_recreation_on_the_water,fishing,football,volleyball,table_tennis,tennis,cycling,distance_from_kazan,cost_of_stay_per_day,short_description,main_feature) VALUES
                                                                                                                                                                                                                                                                                                                                                           ('кемпинг  "Шторм"  ','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','РїРѕСЃС‘Р»РѕРє РЈСЂРјР°РЅС‡Рµ','','"О кемпинге
Всего 30 мин от Казани!


Если вы планируете провести время на природе с комфортом, увидеть закаты на берегу реки, насладиться звездным небом и песнями у костра, кемпинг ""Шторм"" идеально подойдёт для вас.


На территории кемпинга есть все для вашего удобства - кафе с мебелью и посудой, спортивные и детские площадки, душевая и туалетные комнаты, беседки, мангальная зона с дровами и даже бассейн!


В пешей доступности находится красивый подвесной мост и озеро."
','+7 (843) 210-09-18','','РєРµРјРїРёРЅРі-С€С‚РѕСЂРј.СЂС„',16,23.72,13,13,10,-3.4,-9.6,9,0,2,1,0,1,1,1,1,14,4000,'Если вы планируете провести несколько дней на природе с комфортом, увидеть закаты на берегу реки, насладиться звездным небом и песнями у костра, кемпинг "Шторм" идеально подойдёт для вас.','Шатер на 2-4 чел. от 5500 руб.'),
                                                                                                                                                                                                                                                                                                                                                           ('глемпинг GLAMPTOWN','Р РѕСЃСЃРёСЏ','Р РµСЃРїСѓР±Р»РёРєР° РўР°С‚Р°СЂСЃС‚Р°РЅ','РљР°Р·Р°РЅСЊ','РЎРќРў РњРµРґРёРє','594','Глэмпинг Glamptown – прекрасное место для романтического отдыха или уик-энда с друзьями. Находится он среди хвойных лесов рядом с небольшой речкой, это и создает атмосферу уединения с природой. А расположение в черте города Казани позволяет пользоваться благами цивилизации – на территорию глэмпинга можно заказать доставку готовой еды и продуктов.
','','info@campglamp.ru','https://campglamp.ru/catalog/glamptown',13,8.72,7,11,11,-1.4,-11.28,5,3,1,1,0,0,0,0,0,14,4700,'Глэмпинг Glamptown – прекрасное место для романтического отдыха или уик-энда с друзьями. Находится он среди хвойных лесов рядом с небольшой речкой, это и создает атмосферу уединения с природой. А расположение в черте города Казани позволяет пользоваться благами цивилизации – на территорию глэмпинга можно заказать доставку готовой еды и продуктов.','Домик на двоих от 5000 руб.');

INSERT INTO public.photos (id_hotel,link) VALUES
                                              (1,'https://sun9-68.userapi.com/impg/1OA3pZYDCmVTLyidIRlXUdQQkLMe-4E-bC7rlA/v_nRL4EIcO4.jpg?size=686x532&quality=95&sign=5643e6a6441227e230f2680b0ddf5f05&type=album'),
                                              (1,'https://sun9-60.userapi.com/impg/ZgkrGZ6p4k-wvIOkKUyYunK0AXyXTqoyz38sUg/V4lWX7FZILQ.jpg?size=719x544&quality=95&sign=784d709f5b081afd56a3bcb054f9337a&type=album'),
                                              (1,'https://sun2.ufanet.userapi.com/impg/g6OUYZDONrWaYuhBRfQs27KMCCi6KAOmlWNBdw/xpdaqIuApi8.jpg?size=740x549&quality=95&sign=faab58ef26d3a8412ee33c977f97a3cb&type=album'),
                                              (1,'https://sun9-25.userapi.com/impg/Mnhc4KvkjYBc5CrUpGq8WlpYEmDP6KTEcnVtGQ/kQTv-3OIXGw.jpg?size=902x572&quality=95&sign=7242b5b778c22da029fc48f5f3cf9742&type=album'),
                                              (2,'https://sun9-57.userapi.com/impg/_Pvj0qjC1v-SuBO0m_frRWS9W8pw9Mub_SuCqA/yx0YX0lHdrk.jpg?size=809x519&quality=95&sign=a7f27b87c81bd1cb0e8f02e8f31819bd&type=album'),
                                              (2,'https://sun9-28.userapi.com/impg/y5dBwzUJjVYifekeqzOVljkez08CVcaAn-bosA/KRlSdOeJYp0.jpg?size=1280x853&quality=95&sign=3e17e728c0002f527ad88b28abe01529&type=album'),
                                              (2,'https://sun9-2.userapi.com/impg/reV3ySSVj1BN3WlPIqYJtg6dLImExKx-tkedgA/xn-RKZtb4_4.jpg?size=1280x1280&quality=95&sign=1a65da6929376748fd1dee2477393608&type=album'),
                                              (2,'https://sun9-80.userapi.com/impg/2e2CRh-U9tpAHAuFVZqbnJTbZ8QAJl1d_sVlGA/JXHXA0fZA-8.jpg?size=1280x1280&quality=95&sign=06d272ed1778ad2615a665826e1ccc46&type=album'),
                                              (2,'https://sun9-48.userapi.com/impg/I8t_aadNC5DoPNczdG-E28ngCGjqag33BN2MIw/VxdQTn9op-0.jpg?size=1200x800&quality=95&sign=79aae8c99621cde994933fa18832e97f&type=album'),
                                              (2,'https://sun9-79.userapi.com/impg/3SEoPIO-yy0cZdBoLcCAYcSIwwvBbyH6KsgbFQ/Jfljv0EdlJM.jpg?size=740x480&quality=95&sign=77d92eedecef6bda4e64fdac2b8c3f5d&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (3,'https://sun9-15.userapi.com/impg/cZ4731hhmbFFFMG_hQtyVdFh1Hj7sus1hI2dQg/EzaOw2O_Mp0.jpg?size=801x451&quality=95&sign=c7c94e0da27a761aac19fe065f2002b9&type=album'),
                                              (3,'https://sun9-35.userapi.com/impg/mo34S8fUKyvOtJLU1WHLPwn7lS6tLEsXQhEGuA/7ByEW1BB_JQ.jpg?size=802x450&quality=95&sign=30c0d5ca61e1ddc85d8aa912eb063cfa&type=album'),
                                              (3,'https://sun9-24.userapi.com/impg/Vg6QV62foCMxTqHn9K-AXHYsjgCq5-pFbmVwLQ/XvCbarwshoo.jpg?size=798x451&quality=95&sign=8a5cdd6501d7edab184520fb9ce737b8&type=album'),
                                              (4,'https://sun9-54.userapi.com/impg/T6oI61BuMvOa61fr3BBML9dEoMburFgYCqYvuw/2tR-_Dz3NkA.jpg?size=388x303&quality=95&sign=8beb4b7d46fbed445bf39eb52103fa7b&type=album'),
                                              (4,'https://sun9-3.userapi.com/impg/anKd8XopdFhpkddabO9wITdP7kLoUCVmoOyTVg/yxETkanxObA.jpg?size=435x399&quality=95&sign=b77b59e58c139870742e1ade5b90f3fe&type=album'),
                                              (4,'https://sun9-80.userapi.com/impg/yfswivktmTwV9rxebZ8AXSoaXCxE4Sm2F9Vsiw/U-oXqVsKkKY.jpg?size=437x403&quality=95&sign=cc24f994ed58904ce2d34f5752fc226e&type=album'),
                                              (4,'https://sun9-70.userapi.com/impg/O77z54WIjvsvrGEP2DyeBb7eGK8r5H_QBcm4uQ/mHFswOhCbpQ.jpg?size=447x386&quality=95&sign=d077da3eae27552f60fe5d9c39e74dc2&type=album'),
                                              (5,'https://sun9-21.userapi.com/impg/YwDAsyflbgyAEtY0n7wdo9SYCvCGc4xcmp3fvA/0sGKQ7quo0Y.jpg?size=647x494&quality=95&sign=04beb9e927992762dda7d1aba0abe89a&type=album'),
                                              (5,'https://sun9-31.userapi.com/impg/FiB4HSyKT-FbCN0KpQIqle56dmL6dv9RHLXp0g/xrV1k2uNQSQ.jpg?size=757x514&quality=95&sign=feeb8cb6916a0a55e9d7a6b29a5f9972&type=album'),
                                              (5,'https://sun9-17.userapi.com/impg/Rkls5S89K1mPHUQxqD0A69j3VrY_5mOonE8QTA/euQOg3noopg.jpg?size=1020x424&quality=95&sign=cdc6aa58781e39c998048fef8e7f9816&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (5,'https://sun9-14.userapi.com/impg/yvgNwttrAiilNV4vh-yTS3nEerykxaZabOqwiw/mwvXmtFbRkc.jpg?size=876x562&quality=95&sign=67721b28e0483c317b9186189611ee97&type=album'),
                                              (5,'https://sun9-34.userapi.com/impg/MfuxSwkJClrXOqWlBUwwqewd7Qxi63fNw51p2A/EhWrYd4mTtE.jpg?size=878x550&quality=95&sign=4b237dca85710d91ad1f1ba04fa84346&type=album'),
                                              (5,'https://sun9-26.userapi.com/impg/KTTBBY_4gmeqeY-5rENjB4Qji5H-qyY6WKKGhg/6qND-_p7z_k.jpg?size=539x303&quality=95&sign=80724c003400e6387e1728cc04a24699&type=album'),
                                              (6,'https://sun9-34.userapi.com/impg/V87hYGUtvC3yE9motYsiHr8n6_hAphOOynwq_w/B163-kAJ__I.jpg?size=348x321&quality=95&sign=fb712c6f8d612bb80ddd66703a7444ee&type=album'),
                                              (6,'https://sun9-7.userapi.com/impg/JsuQv5rZl2J8oWN7aIaegOI3r5K8kT2H9lqETg/ThPVm-lIqLU.jpg?size=337x277&quality=95&sign=8f395cd20662cb87e8fdebd9e6336330&type=album'),
                                              (6,'https://sun9-80.userapi.com/impg/0QsFsk37B9_gJv6yXQlWJmwYHNvXKqDRGe6OmA/6R3sbAuLLPc.jpg?size=180x228&quality=95&sign=bcac64a1a15f003c8da5391c4df4e11b&type=album'),
                                              (6,'https://sun9-56.userapi.com/impg/AinADJIhUb5apxXKYq4Mu_Ai3jTfQ411MrJHPg/wbbsyKDFl3c.jpg?size=183x273&quality=95&sign=9339f64115638d0511d2a645a22973e4&type=album'),
                                              (6,'https://sun9-58.userapi.com/impg/JInZEc8yhlxKU6GGKJWvmdJuS15vTwk3zHZe7w/4uHjoLmzCaY.jpg?size=182x279&quality=95&sign=d1385c2f1dac9916ac3b4dc31a5e9962&type=album'),
                                              (7,'https://sun9-52.userapi.com/impg/bDOB8e5AYXMzNdUnk1qWd3T6b26pOuei2_me_A/cJXAkAtJ62Y.jpg?size=1200x800&quality=95&sign=9415d37ea5cf10634e34bb71ef7ce7f5&type=album'),
                                              (7,'https://sun9-4.userapi.com/impg/5y7n8hwmVLC4spVQCsNNBYRa56I0dFPxI46Kug/Vedo-mvGaPE.jpg?size=1200x800&quality=95&sign=272494647d71a24e68fc61aa376ab4b8&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (7,'https://sun9-16.userapi.com/impg/ewZlaqMGfM_7dWTfFFA9NHdjL6lPduxtMzQYeg/38ZlxhXprnU.jpg?size=1200x800&quality=95&sign=8390084356547e30560282abceb3ad9c&type=album'),
                                              (7,'https://sun9-59.userapi.com/impg/V3Fw4OufMksDSvg3z4Expsxay_PlJ0CzeeuMMA/50jMZC0luhw.jpg?size=1200x800&quality=95&sign=c8f9e2ea84da6395adef6c264f704dc3&type=album'),
                                              (7,'https://sun9-47.userapi.com/impg/y1r7O-5DLdqODKpzLwroPiw-mxoiJPn-WyaUDA/JJGBI9RPz4M.jpg?size=1200x800&quality=95&sign=866b34a829f4d650db30d00895f02e97&type=album'),
                                              (7,'https://sun9-80.userapi.com/impg/srQppXNRsR59z_RRl9TesMFM7pDfauEnS2rCMw/uIeFTlpKXr8.jpg?size=1200x828&quality=95&sign=c38ed2e9c3dfd2362489afe9ace09006&type=album'),
                                              (7,'https://sun9-70.userapi.com/impg/cw44mQ4IeXTUVt0T_GzeJJCIEMa7AeZpaEEGUQ/NOTNJZ1ahKU.jpg?size=1200x800&quality=95&sign=9f8c062c63c61d33737eb9236cf5f2b5&type=album'),
                                              (7,'https://sun9-45.userapi.com/impg/lGEjo22BE47lL3KVmk1NVT1WD9m0W2eYxj3P5Q/IpwnUEF5OJI.jpg?size=1200x800&quality=95&sign=56aafafa146abf3668c3d2f109841d16&type=album'),
                                              (8,'https://sun9-43.userapi.com/impg/0iWkmXQRIgiGb5_hVA-tx8IdoEFszAfxdeKQ5Q/gRGPAffD598.jpg?size=415x507&quality=95&sign=e222de48d783c0c5fbf608da8abd6c61&type=album'),
                                              (8,'https://sun9-65.userapi.com/impg/IO8mVqkK5MNaDeQDE61AuMo_oLU0i_SClspnwg/iqn-JasscPE.jpg?size=450x492&quality=95&sign=88db56cfc5c1f33f58fefcb40ebd9c01&type=album'),
                                              (8,'https://sun2.ufanet.userapi.com/impg/aHgPy_DY5LEYjJg1XG_wkeCUydKYIl-1vx0IIg/a9tG2iYkLsc.jpg?size=451x458&quality=95&sign=5cd23fbf5a1fcd28c47fca9a68438ead&type=album'),
                                              (8,'https://sun9-28.userapi.com/impg/Q8zWNPlx2PhsaryrPmLoMKtHnXnN5vkhGzayTw/lAtPqz3_aPI.jpg?size=450x340&quality=95&sign=d0a5797c5e5c37cc597acdb7ebaaa977&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (9,'https://sun9-80.userapi.com/impg/4OJvFsNtB9vbW-P-6pYqp_4pmgHfGWXk9lGaIA/hBqYsgJKooA.jpg?size=1280x848&quality=95&sign=430581eb6c90461b4f0d53560b52fb22&type=album'),
                                              (9,'https://sun9-10.userapi.com/impg/fPBtQ6nmjq3zbvRugcY7IQS3MZmSRle9lV75sw/G5latAMuAik.jpg?size=670x404&quality=95&sign=02d84ca4fe630befe2f9240a6d6d6e1b&type=album'),
                                              (9,'https://sun9-58.userapi.com/impg/rc5BaJ2VEllLeOHSu0gwL_m14BjDRK9oTzVJ4g/T8NJ7fqvv08.jpg?size=765x501&quality=95&sign=34c71bda81be7bf553a25f5a0eb8d9ed&type=album'),
                                              (9,'https://sun9-44.userapi.com/impg/EQgUhINWOcEGf0fbjdO7aDKhkx1UJ1VftBupyA/WJdjqHOcNyk.jpg?size=864x1080&quality=95&sign=4c3f3ae49a0ef274f6c2732c17fce4db&type=album'),
                                              (9,'https://sun9-14.userapi.com/impg/lVwMq6c50f6XxPjPZCX_JSleL4jNkFBhfZ6Y5g/64zQd0DkJJU.jpg?size=864x1080&quality=95&sign=9a7423cfad4d4ccaf9cb095dae603450&type=album'),
                                              (9,'https://sun9-58.userapi.com/impg/RTH9nTIVS7My3whSfzp2Bo5BMk8PG0-Ihi6v3A/xf7z8oKX3zk.jpg?size=864x1080&quality=95&sign=79002ad53947f4d66c08d12db7b332dc&type=album'),
                                              (9,'https://sun9-13.userapi.com/impg/7OWyfjr-qSwfzkbX8f9p44FSAi9DfEXuAtr9Ug/p4lcuvCtcSE.jpg?size=864x1080&quality=95&sign=06f4496b92535abd73c301b4ec660b7a&type=album'),
                                              (9,'https://sun9-46.userapi.com/impg/8VjtKF4wqEDxsYaM8D-r0mSoNj8lUZvRyW2n7A/mTu0IgB0iAc.jpg?size=864x1080&quality=95&sign=f8716053482944d206c460f8dd15df59&type=album'),
                                              (9,'https://sun9-4.userapi.com/impg/kZC8rCuUwEBUEZFLBJN2UEpAXFMiHarVfOYr_w/t9uXwbXulUY.jpg?size=864x1080&quality=95&sign=900c20552a3b1c4e4a92f5e1dc051fed&type=album'),
                                              (9,'https://sun9-76.userapi.com/impg/Z4QeI7KEHTOe6NtVgnTZMppJKQ7gNtJapvZFzQ/ApupPWMoy_M.jpg?size=864x1080&quality=95&sign=e5b5201fb43cb1622e1e5f4af16df21d&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (10,'https://sun9-67.userapi.com/impg/34EfFx0AdDa9LALOORYJ_xsSR6SVeQLd3Nxz5Q/A0QQzFR7pYg.jpg?size=374x312&quality=95&sign=0d979137300f16ac501b3e3ef0098ab1&type=album'),
                                              (10,'https://sun9-66.userapi.com/impg/h4UqoeG-65KK4zyuQjTcGhPzF7QTgunNMVrsew/YYG_hMYfDcA.jpg?size=271x225&quality=95&sign=5a041d06cdf5158866c796a8bc61072a&type=album'),
                                              (10,'https://sun9-24.userapi.com/impg/aKa4DD8e3uHviBi63rjBBmRaYj2l0N36Hf-bRg/c4Pb_Oyeyt0.jpg?size=271x212&quality=95&sign=bc6e0a62d4f3d4dd9a3f8c50abecd570&type=album'),
                                              (10,'https://sun9-16.userapi.com/impg/HokmLFOql9pr9yRQzhk2YiVDlZLD2A5VcQZ6AA/SmbgfnNyjrs.jpg?size=269x226&quality=95&sign=eef220bca9645346da219b90d847de97&type=album'),
                                              (11,'https://sun9-27.userapi.com/impg/cFjf7THYMzJ4mtP-J8M_XHXCqTEgRXwHPgSvUQ/QZZjY0FOL68.jpg?size=1092x489&quality=95&sign=cbc9655801085745e83690e45f75cef8&type=album'),
                                              (11,'https://sun9-15.userapi.com/impg/_cXgY9b60WHul_fbUkeVB7P3rgGAWR8_dhz31A/0GB10jQRwH0.jpg?size=1280x853&quality=95&sign=6c5290965d8c7cb872125bd080f1445f&type=album'),
                                              (11,'https://sun9-13.userapi.com/impg/d4596DQYsiJV_iP2DXyBz0O7Twby1pNA1ufkfA/Q--XGy1ucYc.jpg?size=1280x801&quality=95&sign=60fa43fd0b7450ee88ff0e588ffaa31d&type=album'),
                                              (11,'https://sun9-9.userapi.com/impg/tEehY3qOJHq_VQ-4t_VqixqBKzg0m7nab6gs9g/zYW3T63IV1Y.jpg?size=1280x853&quality=95&sign=b18313ce367c380bbc53fe1a4f04158e&type=album'),
                                              (11,'https://sun9-48.userapi.com/impg/_b-FTkbcVHnOibNVwtVU5W5mON_JwkKkH_ej-w/jUiaVXx8e04.jpg?size=1280x853&quality=95&sign=7e2cc148e69fa0de87385be2b99c799e&type=album'),
                                              (11,'https://sun9-74.userapi.com/impg/ReWaZZ7jJTVAJu4LxI670UxHGLPAKwaAxdmhTw/1sas-exqjLc.jpg?size=1280x1011&quality=95&sign=eb0c6225919f4c10bdeb08a834823f98&type=album');
INSERT INTO public.photos (id_hotel,link) VALUES
                                              (11,'https://sun9-41.userapi.com/impg/05y7HJdcmJpmrfVdqGr8ETdiY4BHspxIBvLknw/mD_8F_0fu1Y.jpg?size=1280x853&quality=95&sign=15cf192c20a69a133583d79b68ae0723&type=album'),
                                              (11,'https://sun9-18.userapi.com/impg/YJ6OHv_Yc2HugXPFSUrST7qn2gFHtYlHbIHH9A/IgYZL2eSs9w.jpg?size=1280x853&quality=95&sign=947760a71d891b587d53f42691a1eb18&type=album'),
                                              (11,'https://sun9-16.userapi.com/impg/fXvld7kwTLmFG9lMxttb59y2nGh9DMAkiKmcBw/kEBM2ms_quc.jpg?size=1280x853&quality=95&sign=c0b266a043e99a7cda249d0292905217&type=album'),
                                              (11,'https://sun9-2.userapi.com/impg/r-zloJF8K8-bvm7ieYeZzAT9DR_SPWaRBA5hKA/qi55pnRYdkM.jpg?size=1280x853&quality=95&sign=935da9b38b8264d9c2d7cf4ed2287983&type=album'),
                                              (12,'https://sun9-74.userapi.com/impg/mEcc_iKKdMV6jp_TkDuv9BmVdTxaWAAkt6uRQw/ORvZmQQiuik.jpg?size=630x420&quality=95&sign=8ca3a774a9925f51d6ddcd8ced3b7274&type=album');



INSERT INTO public.residence_history (check_in_date,check_out_date,total_cost,review,grade,id_user,id_hotel) VALUES
                                                                                                                 ('2023-05-02','2023-05-24',1000.0,'Good',4,3,1),
                                                                                                                 ('2023-05-09','2023-05-19',2.0,'Bad',1,3,1),
                                                                                                                 ('2023-05-01','2023-06-01',2000.0,'Good',4,3,2),
                                                                                                                 ('2023-05-23','2023-05-31',2000.0,'Great',5,2,1),
                                                                                                                 ('2023-05-02','2023-05-25',2000.0,'so-so',3,1,4),
                                                                                                                 ('2023-05-02','2023-05-19',2500.0,'Good',4,2,7);


INSERT INTO public.users (first_name,last_name,otchestvo,email,phone_num,"password") VALUES
                                                                                         ('','','','zero_user@mail.ru','','12345678'),
                                                                                         ('Timber','','','timber@mail.ru','','12345678'),
                                                                                         ('Mark','','','mark@mail.ru','','12345678'),
                                                                                         ('Karen','','','karen@mail.ru','','12345678');
